---
title: "DESeq2_MACS_P4_Bulk"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
options(digits=4)
library(ggplot2)
library(cowplot)
library(DESeq2)
library(org.Mm.eg.db)
library(AnnotationDbi)
library(tidyverse)
```
```{r import}
load("../1.align/txi.rsem.RData")
metadata <- read.csv("metadata.csv", stringsAsFactors = TRUE)
metadata$Trt <- factor(metadata$Trt, levels=c("SAL","LPS"))
rownames(metadata) <- metadata$ID
all.equal(colnames(txi.rsem$counts), as.character(metadata$ID))
```

```{r dds, message=FALSE, warning=FALSE}
dds <- DESeqDataSetFromTximport(txi.rsem, colData = metadata, design = ~ Group)
# filter low expressed genes and samples
samp <- colData(dds)$Trt == "SAL" & dds$ID != "CS6" & dds$ID != "MS6" & dds$ID != "MS7"
dds <- dds[,samp]
keep <- rowSums(counts(dds)) >= 50
table(keep)
dds <- dds[keep,]

# add in gene symbols
genes <- gsub("\\..*","",rownames(dds))
library(AnnotationHub)
ah <- AnnotationHub()
edb <- ah[["AH53222"]]
symbol <- mapIds(edb, keys=genes, column="SYMBOL", keytype="GENEID", multiVals="first")
mcols(dds) <- cbind(mcols(dds), symbol)

dds <- DESeq(dds)
resultsNames(dds)

# difference between MIA and CON in SAL
summary(results(dds, name="Group_MIA_vs_CON", alpha=0.05))
# up:1066 down: 968

MvCinSAL <- results(dds, name="Group_MIA_vs_CON", alpha=0.05)
MvCinSAL$gene <- symbol
```

```{r}
library(pheatmap)
vsd <- vst(dds, blind=FALSE)
rownames(vsd) <- symbol

df <- as.data.frame(colData(dds)["Group"])
ann_colors = list(Group = c(CON = "black", MIA = "red"))

DEG <- order(MvCinSAL$pvalue)[1:1000]
pheatmap(assay(vsd)[DEG,], cluster_rows=TRUE, show_rownames=FALSE, cluster_cols=F, annotation_col=df, scale="row", border_color = NA, col = colorRampPalette(c("navy", "white", "firebrick3"))(50), annotation_colors = ann_colors, main="MIA vs CON in SAL")
# scaled transformed counts
```

### Volcano plots of DEGs between Group
```{r, echo=FALSE, message=FALSE, warning = FALSE, fig.height=7, fig.width=5}
library(EnhancedVolcano)
group <- lfcShrink(dds, coef = "Group_MIA_vs_CON", type = 'apeglm')
group$symbol <- mcols(dds)$symbol

EnhancedVolcano(group, lab = group$symbol, x = 'log2FoldChange', y = 'pvalue',
    title = 'Group_MIA_vs_CON', subtitle = "", pCutoffCol = 'padj',
    colAlpha = 1, col=c('grey', 'grey', 'black', 'black'), 
    ylim = c(0, 35), xlim = c(-3,5),
    pCutoff = 0.05, FCcutoff = 0.5, pointSize = 2.0, labSize = 3)
```

```{r}
sessionInfo()
```