---
output:
  html_document: 
    df_print: default
    highlight: haddock
    keep_md: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---
# **ELISA data** for serum IL-6 after LPS or SAL treatment
Data analysis of serum protein expression of IL-6 after treatment with saline (SAL) or 4500 EU/g lipopolysaccharide (LPS) for 18 hours. Data are pg/mL.

## Samples
```{r, echo=TRUE, message=FALSE}
library(ggplot2)
library(cowplot)
library(lme4)
library(lmerTest)
library(multcomp)
library(tidyverse)
```
```{r}
data <- read.csv("210309.csv", header=TRUE, stringsAsFactors = TRUE)
data$TRT <- relevel(data$TRT, ref="SAL")
```

## Plot data
```{r, echo=F, fig.width=5, fig.height=3}
data %>% filter(Group=="CON" | Group =="MIA") %>% ggplot(., aes(x=TRT, y=log2(Serum.IL.6+1), fill=Group)) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(dodge.width = 0.75, jitter.width = 0.3)) + scale_fill_manual(values= c("grey","red")) + labs(x="",y="Serum IL-6 (log2, au)",fill="") + theme(legend.position="none") + theme_cowplot()

data %>% filter(Group=="CON:CON" | Group =="CON:PLX" | Group=="MIA:CON" | Group =="MIA:PLX", TRT =="LPS") %>% ggplot(., aes(x=TRT, y=log2(Serum.IL.6+1), fill=Group)) + geom_boxplot(outlier.shape = NA) + geom_point(position = position_jitterdodge(dodge.width = 0.75, jitter.width = 0.3)) + scale_fill_manual(values= c("grey", "turquoise3","red", "purple3")) + labs(x="",y="Serum IL-6 (log2, au)",fill="") + theme(legend.position="none") + theme_cowplot() + ylim(0,16)

```

## Linear Mixed Effect Model MIA vs CON
```{r, echo=FALSE}
MvC <- data %>% filter(Group=="CON" | Group =="MIA")
MvC$Group2 <- factor(MvC$Group2, levels = c("CON:SAL", "CON:LPS", "MIA:SAL", "MIA:LPS"))
a<-count(unique(MvC %>% filter(Group2 == "CON:SAL") %>% select(Litter)))
b<-count(unique(MvC %>% filter(Group2 == "CON:LPS") %>% select(Litter)))
c<-count(unique(MvC %>% filter(Group2 == "MIA:SAL") %>% select(Litter)))
d<-count(unique(MvC %>% filter(Group2 == "MIA:LPS") %>% select(Litter)))
n <- rbind(table(MvC$Group2), c(a,b,c,d))
rownames(n) <- c("# mice", "# litters")
n

e <- MvC %>% filter(Group2=="CON:SAL") %>% mutate(pval = shapiro.test(log2(Serum.IL.6+1))$p.value)
f <- MvC %>% filter(Group2=="CON:LPS") %>% mutate(pval = shapiro.test(log2(Serum.IL.6+1))$p.value)
g <- MvC %>% filter(Group2=="MIA:SAL") %>% mutate(pval = shapiro.test(log2(Serum.IL.6+1))$p.value)
h <- MvC %>% filter(Group2=="MIA:LPS") %>% mutate(pval = shapiro.test(log2(Serum.IL.6+1))$p.value)
tmp=rbind(e$pval[1], f$pval[1], g$pval[1], h$pval[1])
rownames(tmp)=c("CON:SAL","CON:LPS","MIA:SAL","MIA:LPS")
colnames(tmp)=c("Shapiro Test for Normality")
round(tmp,3)
rm(a,b,c,d,e,f,g,h,n,tmp)
```
```{r}
lme.fit <- lmer(log2(Serum.IL.6+1) ~ Group*TRT+(1|Litter), data=MvC)
summary(lme.fit)
```

## Linear Mixed Effect Model CON:CON, CON:PLX, MIA:CON, MIA:PLX all after LPS
```{r, echo=FALSE}
Rescue <- data %>% filter(Group=="CON:CON" | Group =="CON:PLX" | Group=="MIA:CON" | Group =="MIA:PLX", TRT =="LPS")
Rescue$Group <- factor(Rescue$Group, levels = c("CON:CON", "CON:PLX", "MIA:CON", "MIA:PLX"))
a<-count(unique(Rescue %>% filter(Group == "CON:CON") %>% select(Litter)))
b<-count(unique(Rescue %>% filter(Group == "CON:PLX") %>% select(Litter)))
c<-count(unique(Rescue %>% filter(Group == "MIA:CON") %>% select(Litter)))
d<-count(unique(Rescue %>% filter(Group == "MIA:PLX") %>% select(Litter)))
n<-cbind(table(Rescue$Group, Rescue$TRT), c(a,b,c,d))
colnames(n) <- c("SAL", "LPS", "# litters")
n

e <- Rescue %>% filter(Group=="CON:CON") %>% mutate(pval = shapiro.test(log2(Serum.IL.6+1))$p.value)
f <- Rescue %>% filter(Group=="CON:PLX") %>% mutate(pval = shapiro.test(log2(Serum.IL.6+1))$p.value)
g <- Rescue %>% filter(Group=="MIA:CON") %>% mutate(pval = shapiro.test(log2(Serum.IL.6+1))$p.value)
h <- Rescue %>% filter(Group=="MIA:PLX") %>% mutate(pval = shapiro.test(log2(Serum.IL.6+1))$p.value)
tmp=rbind(e$pval[1], f$pval[1], g$pval[1], h$pval[1])
rownames(tmp)=c("CON:CON","CON:PLX","MIA:CON","MIA:PLX")
colnames(tmp)=c("Shapiro Test for Normality")
round(tmp,3)
rm(a,b,c,d,e,f,g,h,n,tmp)
```
```{r}
lme.fit <- lmer(log2(Serum.IL.6+1) ~ Group+(1|Litter), data=Rescue)
summary(lme.fit)
```

### Reproducibility info
```{r, echo=FALSE}
Sys.time()
devtools::session_info()
```