---
title: "DESeq2_FACS_Adult_Rescue"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, message=FALSE, error=FALSE, warning=FALSE}
options(digits=3)
library(tidyverse)
library(ggplot2)
library(cowplot)
library(DESeq2)
library(org.Mm.eg.db)
library(ggrepel)
library(AnnotationDbi)
library(AnnotationHub)
library(epiR)
```
```{r import}
load("../1.align/txi.rsem.RData")
metadata <- read.csv("metadata.csv", stringsAsFactors = TRUE)
metadata$Trt <- factor(metadata$Trt, levels=c("SAL","LPS"))
rownames(metadata) <- metadata$ID
all.equal(colnames(txi.rsem$counts), rownames(metadata))
```

# Differential gene expression for design: Group1 + Trt + Group1:Trt
```{r dds, warning=FALSE, message = FALSE}
dds <- DESeqDataSetFromTximport(txi.rsem, colData = metadata, design = ~ Group1 + Trt + Group1:Trt)
samp <- colData(dds)$ID != "CCL3" & colData(dds)$ID != "MPS1"

# filter low expressed genes
keep <- rowSums(counts(dds)) >= 80
table(keep)
dds <- dds[keep, samp]

# add in gene symbols
genes <- gsub("\\..*","",rownames(dds))
ah <- AnnotationHub()
edb <- ah[["AH53222"]]
symbol <- mapIds(edb, keys=genes, column="SYMBOL", keytype="GENEID", multiVals="first")
mcols(dds) <- cbind(mcols(dds), symbol)


dds <- DESeq(dds)
resultsNames(dds)
```

# LPS Response
```{r}
# The effect of treatment in CON:CON
LvSinCON_CON <- results(dds, contrast=c("Trt","LPS","SAL"), alpha=0.05)
summary(LvSinCON_CON)  # up:1570 down: 1464
LvSinCON_CON$gene <- symbol

# The effect of treatment in CON:PLX
LvSinCON_PLX <- results(dds, list( c("Trt_LPS_vs_SAL","Group1CON_PLX.TrtLPS")), alpha=0.05)
summary(LvSinCON_PLX)# up:2149 down: 1969
LvSinCON_PLX$gene <- symbol

# The effect of treatment in MIA:CON
LvSinMIA_CON <- results(dds, list( c("Trt_LPS_vs_SAL","Group1MIA_CON.TrtLPS")), alpha=0.05)
summary(LvSinMIA_CON)# up:1738 down: 1531
LvSinMIA_CON$gene <- symbol

# The effect of treatment in MIA:PLX
LvSinMIA_PLX <- results(dds, list( c("Trt_LPS_vs_SAL","Group1MIA_PLX.TrtLPS")), alpha=0.05)
summary(LvSinMIA_PLX)# up:1474 down: 1366
LvSinMIA_PLX$gene <- symbol
```

# LPS Response in CON_CON vs MIA_CON
```{r}
LPS_MC_CC <- merge(as.data.frame(LvSinCON_CON), as.data.frame(LvSinMIA_CON), by = "row.names", all.x = TRUE)

rownames(LPS_MC_CC) <- LPS_MC_CC$Row.names
colnames(LPS_MC_CC) <- c("gene.id","baseMean.CC","log2FC.CC","lfcSE.CC","stat.CC","pval.CC","padj.CC", "gene.name.CC", "baseMean.MC","log2FC.MC","lfcSE.MC","stat.MC","pval.MC","padj.MC", "gene.name")

#Assign the Group variable for coloring 4-way plot 
for (i in c(1:nrow(LPS_MC_CC))){
  if (LPS_MC_CC$padj.CC[i]<0.05 & (!is.na(LPS_MC_CC$padj.CC[i]))){
    LPS_MC_CC$CCSig[i]='YES'
  }
  else {
    LPS_MC_CC$CCSig[i]='NO'
  }
}

for (i in c(1:nrow(LPS_MC_CC))){
  if (LPS_MC_CC$padj.MC[i]<0.05 & (!is.na(LPS_MC_CC$padj.MC[i]))){
    LPS_MC_CC$MCSig[i]='YES'
  }
  else {
    LPS_MC_CC$MCSig[i]='NO'
  }
}

for (i in c(1:nrow(LPS_MC_CC))){
  if (LPS_MC_CC$CCSig[i]=='YES' & LPS_MC_CC$MCSig[i]=='NO'){
    LPS_MC_CC$Group[i]=1 }
  else if (LPS_MC_CC$CCSig[i]=='NO' & LPS_MC_CC$MCSig[i]=='YES'){
    LPS_MC_CC$Group[i]=2}
  else if (LPS_MC_CC$CCSig[i]=='YES' & LPS_MC_CC$MCSig[i]=='YES'){
    LPS_MC_CC$Group[i]=3}
  else {
    LPS_MC_CC$Group[i]=4}
  
}
dim(LPS_MC_CC)
table(LPS_MC_CC$Group)
LPS_MC_CC <- LPS_MC_CC %>% dplyr::filter(log2FC.CC < 15 & log2FC.CC > -15 & log2FC.MC < 15 & log2FC.MC > -15)
LPS_MC_CC.final<-subset(LPS_MC_CC, LPS_MC_CC$Group != 4)

ggplot(data = LPS_MC_CC.final, aes(x = log2FC.CC, y = log2FC.MC, color=factor(Group))) + geom_point() + scale_color_manual(values = c("black", "red","grey"), labels = c("CON:CON","MIA:CON","both")) + geom_abline(slope=1, size=0.5) + labs(x="Con:CON logFC",y="MIA:CON logFC", color="") + theme_cowplot() + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + xlim(-15, 15) + ylim(-15, 15) + labs(title = "MC vs CC")

dim(LPS_MC_CC.final %>% dplyr::filter(log2FC.CC>0 & log2FC.MC >0 & log2FC.MC > log2FC.CC)) # 1048
dim(LPS_MC_CC.final %>% dplyr::filter(log2FC.CC>0 & log2FC.MC >0 & log2FC.MC < log2FC.CC)) # 1110
dim(LPS_MC_CC.final %>% dplyr::filter(log2FC.CC<0 & log2FC.MC <0 & log2FC.MC > log2FC.CC)) # 1166
dim(LPS_MC_CC.final %>% dplyr::filter(log2FC.CC<0 & log2FC.MC <0 & log2FC.MC < log2FC.CC)) # 836
dim(LPS_MC_CC.final %>% dplyr::filter(log2FC.CC>0 & log2FC.MC <0)) # 77
dim(LPS_MC_CC.final %>% dplyr::filter(log2FC.CC<0 & log2FC.MC >0)) # 82


ggplotRegression <- function (fit) {
require(ggplot2)
ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point(color = "grey50") +
  stat_smooth(method = "lm", col = "blue", size=2) +
  labs(subtitle = paste(" Slope =",signif(fit$coef[[2]], 3),
                        " P =",signif(summary(fit)$coef[2,4], 3),
                        "Adj R2 = ",signif(summary(fit)$adj.r.squared, 3),
                        "Intercept =",signif(fit$coef[[1]],3 )
                     ))
}

ggplotRegression(lm(LPS_MC_CC.final$log2FC.MC ~ LPS_MC_CC.final$log2FC.CC, data=LPS_MC_CC.final)) + geom_abline(slope=1) + labs(x="CON:CON log2FC (LPS/SAL)", y="MIA:CON log2FC (LPS/SAL)") + xlim(-15, 15) + ylim(-15, 15) + theme_cowplot() + labs(title = "MC vs CC")

# concordance correlation coefficient
epi.ccc(LPS_MC_CC.final$log2FC.CC, LPS_MC_CC.final$log2FC.MC, ci = "z-transform", conf.level = 0.95)$rho.c
```

# LPS Response in CON_CON vs MIA_PLX
```{r}
LPS_MP_CC <- merge(as.data.frame(LvSinCON_CON), as.data.frame(LvSinMIA_PLX), by = "row.names", all.x = TRUE)

rownames(LPS_MP_CC) <- LPS_MP_CC$Row.names
colnames(LPS_MP_CC) <- c("gene.id","baseMean.CC","log2FC.CC","lfcSE.CC","stat.CC","pval.CC","padj.CC", "gene.name.CC", "baseMean.MP","log2FC.MP","lfcSE.MP","stat.MP","pval.MP","padj.MP", "gene.name")

#Assign the Group variable for coloring 4-way plot 
for (i in c(1:nrow(LPS_MP_CC))){
  if (LPS_MP_CC$padj.CC[i]<0.05 & (!is.na(LPS_MP_CC$padj.CC[i]))){
    LPS_MP_CC$CCSig[i]='YES'
  }
  else {
    LPS_MP_CC$CCSig[i]='NO'
  }
}

for (i in c(1:nrow(LPS_MP_CC))){
  if (LPS_MP_CC$padj.MP[i]<0.05 & (!is.na(LPS_MP_CC$padj.MP[i]))){
    LPS_MP_CC$MPSig[i]='YES'
  }
  else {
    LPS_MP_CC$MPSig[i]='NO'
  }
}

for (i in c(1:nrow(LPS_MP_CC))){
  if (LPS_MP_CC$CCSig[i]=='YES' & LPS_MP_CC$MPSig[i]=='NO'){
    LPS_MP_CC$Group[i]=1 }
  else if (LPS_MP_CC$CCSig[i]=='NO' & LPS_MP_CC$MPSig[i]=='YES'){
    LPS_MP_CC$Group[i]=2}
  else if (LPS_MP_CC$CCSig[i]=='YES' & LPS_MP_CC$MPSig[i]=='YES'){
    LPS_MP_CC$Group[i]=3}
  else {
    LPS_MP_CC$Group[i]=4}
  
}
dim(LPS_MP_CC)
table(LPS_MP_CC$Group)
LPS_MP_CC <- LPS_MP_CC %>% dplyr::filter(log2FC.CC < 15 & log2FC.CC > -15 & log2FC.MP < 15 & log2FC.MP > -15)
LPS_MP_CC.final<-subset(LPS_MP_CC, LPS_MP_CC$Group != 4)

ggplot(data = LPS_MP_CC.final, aes(x = log2FC.CC, y = log2FC.MP, color=factor(Group))) + geom_point() + scale_color_manual(values = c("black", "purple3","grey"), labels = c("CON:CON","MIA:PLX","both")) + geom_abline(slope=1, size=0.5) + labs(x="Con:CON logFC",y="MIA:PLX logFC", color="") + theme_cowplot() + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + xlim(-15, 15) + ylim(-15, 15)+ labs(title = "MP vs CC")

dim(LPS_MP_CC.final %>% dplyr::filter(log2FC.CC>0 & log2FC.MP >0 & log2FC.MP > log2FC.CC)) # 958
dim(LPS_MP_CC.final %>% dplyr::filter(log2FC.CC>0 & log2FC.MP >0 & log2FC.MP < log2FC.CC)) # 975
dim(LPS_MP_CC.final %>% dplyr::filter(log2FC.CC<0 & log2FC.MP <0 & log2FC.MP > log2FC.CC)) # 886
dim(LPS_MP_CC.final %>% dplyr::filter(log2FC.CC<0 & log2FC.MP <0 & log2FC.MP < log2FC.CC)) # 946
dim(LPS_MP_CC.final %>% dplyr::filter(log2FC.CC>0 & log2FC.MP <0)) # 43
dim(LPS_MP_CC.final %>% dplyr::filter(log2FC.CC<0 & log2FC.MP >0)) # 62

ggplotRegression(lm(LPS_MP_CC.final$log2FC.MP ~ LPS_MP_CC.final$log2FC.CC, data=LPS_MP_CC.final)) + geom_abline(slope=1) + labs(x="CON:CON log2FC (LPS/SAL)", y="MIA:PLX log2FC (LPS/SAL)")+ theme_cowplot() + xlim(-15, 15) + ylim(-15, 15) + labs(title = "MP vs CC")

# concordance correlation coefficient
epi.ccc(LPS_MP_CC.final$log2FC.CC, LPS_MP_CC.final$log2FC.MP, ci = "z-transform", conf.level = 0.95)$rho.c
```

# LPS Response in CON_CON vs CON_PLX
```{r}
LPS_CP_CC <- merge(as.data.frame(LvSinCON_CON), as.data.frame(LvSinCON_PLX), by = "row.names", all.x = TRUE)

rownames(LPS_CP_CC) <- LPS_CP_CC$Row.names
colnames(LPS_CP_CC) <- c("gene.id","baseMean.CC","log2FC.CC","lfcSE.CC","stat.CC","pval.CC","padj.CC", "gene.name.CC", "baseMean.CP","log2FC.CP","lfcSE.CP","stat.CP","pval.CP","padj.CP", "gene.name")

#Assign the Group variable for coloring 4-way plot 
for (i in c(1:nrow(LPS_CP_CC))){
  if (LPS_CP_CC$padj.CC[i]<0.05 & (!is.na(LPS_CP_CC$padj.CC[i]))){
    LPS_CP_CC$CCSig[i]='YES'
  }
  else {
    LPS_CP_CC$CCSig[i]='NO'
  }
}

for (i in c(1:nrow(LPS_CP_CC))){
  if (LPS_CP_CC$padj.CP[i]<0.05 & (!is.na(LPS_CP_CC$padj.CP[i]))){
    LPS_CP_CC$CPSig[i]='YES'
  }
  else {
    LPS_CP_CC$CPSig[i]='NO'
  }
}

for (i in c(1:nrow(LPS_CP_CC))){
  if (LPS_CP_CC$CCSig[i]=='YES' & LPS_CP_CC$CPSig[i]=='NO'){
    LPS_CP_CC$Group[i]=1 }
  else if (LPS_CP_CC$CCSig[i]=='NO' & LPS_CP_CC$CPSig[i]=='YES'){
    LPS_CP_CC$Group[i]=2}
  else if (LPS_CP_CC$CCSig[i]=='YES' & LPS_CP_CC$CPSig[i]=='YES'){
    LPS_CP_CC$Group[i]=3}
  else {
    LPS_CP_CC$Group[i]=4}
  
}
dim(LPS_CP_CC)
table(LPS_CP_CC$Group)
LPS_CP_CC <- LPS_CP_CC %>% dplyr::filter(log2FC.CC < 15 & log2FC.CC > -15 & log2FC.CP < 15 & log2FC.CP > -15)
LPS_CP_CC.final<-subset(LPS_CP_CC, LPS_CP_CC$Group != 4)

ggplot(data = LPS_CP_CC.final, aes(x = log2FC.CC, y = log2FC.CP, color=factor(Group))) + geom_point() + scale_color_manual(values = c("black", "turquoise3","grey"), labels = c("CON:CON","CON:PLX","both")) + geom_abline(slope=1, size=0.5) + labs(x="CON:CON logFC",y="CON:PLX logFC", color="") + theme_cowplot() + geom_hline(yintercept = 0) + geom_vline(xintercept = 0) + xlim(-15, 15) + ylim(-15, 15) + labs(title = "CP vs CC")

dim(LPS_CP_CC.final %>% dplyr::filter(log2FC.CC>0 & log2FC.CP >0 & log2FC.CP > log2FC.CC)) # 1497
dim(LPS_CP_CC.final %>% dplyr::filter(log2FC.CC>0 & log2FC.CP >0 & log2FC.CP < log2FC.CC)) # 923
dim(LPS_CP_CC.final %>% dplyr::filter(log2FC.CC<0 & log2FC.CP <0 & log2FC.CP > log2FC.CC)) # 935
dim(LPS_CP_CC.final %>% dplyr::filter(log2FC.CC<0 & log2FC.CP <0 & log2FC.CP < log2FC.CC)) # 1308
dim(LPS_CP_CC.final %>% dplyr::filter(log2FC.CC>0 & log2FC.CP <0)) # 77
dim(LPS_CP_CC.final %>% dplyr::filter(log2FC.CC<0 & log2FC.CP >0)) # 82


ggplotRegression <- function (fit) {
require(ggplot2)
ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point(color = "grey50") +
  stat_smooth(method = "lm", col = "blue", size=2) +
  labs(subtitle = paste(" Slope =",signif(fit$coef[[2]], 3),
                        " P =",signif(summary(fit)$coef[2,4], 3),
                        "Adj R2 = ",signif(summary(fit)$adj.r.squared, 3),
                        "Intercept =",signif(fit$coef[[1]],3 )
                     ))
}

ggplotRegression(lm(LPS_CP_CC.final$log2FC.CP ~ LPS_CP_CC.final$log2FC.CC, data=LPS_CP_CC.final)) + geom_abline(slope=1) + labs(x="CON:CON log2FC (LPS/SAL)", y="CON:PLX log2FC (LPS/SAL)")+ theme_cowplot() + xlim(-15, 15) + ylim(-15, 15) + labs(title = "CP vs CC")

# concordance correlation coefficient
epi.ccc(LPS_CP_CC.final$log2FC.CC, LPS_CP_CC.final$log2FC.CP, ci = "z-transform", conf.level = 0.95)$rho.c
```

## Heatmap
```{r LPS Response Heatmap, fig.height=7, fig.width=4}
library(pheatmap)
LPS <- as.data.frame(cbind(LvSinCON_CON, LvSinCON_PLX, LvSinMIA_CON, LvSinMIA_PLX))
colnames(LPS) <- c("baseMean.CC", "log2FC.CC", "lfcSE.CC","stat.CC", "pval.CC", "padj.CC", "gene.CC","baseMean.CP", "log2FC.CP", "lfcSE.CP", "stat.CP", "pval.CP", "padj.CP", "gene.CP", "baseMean.MC", "log2FC.MC", "lfcSE.MC", "stat.MC", "pval.MC", "padj.MC", "gene.MC", "baseMean.MP", "log2FC.MP", "lfcSE.MP", "stat.MP", "pval.MP", "padj.MP", "gene.MP")

write.csv(LPS, "writes/211005_LPS_all.csv")
rescue <- read.csv("writes/RescueGenes.csv")
sig <- which(LPS$gene.CC %in% rescue$RESCUE)

sorted.LPS <- data.frame(LPS[sig,c(2,9,16,23)])
sorted.LPS <- sorted.LPS[order(sorted.LPS$log2FC.CC),]

paletteLength <- 50
myColor <- colorRampPalette(c("navy", "white", "red"))(paletteLength)
myBreaks <- c(seq(-4, 0, length.out=ceiling(paletteLength/2) + 1), 
              seq(8/paletteLength, 8, length.out=floor(paletteLength/2)))

pheatmap(sorted.LPS, cluster_rows=F, show_rownames=F, cluster_cols=F, scale="none", breaks = myBreaks, col = myColor, main="Rescued LPS Response Genes")
```

```{r}
sessionInfo()
```